@startuml
left to right direction
actor 普通用户

package "图书漂流系统" {

    usecase "个人中心" as UC1
    usecase "系统前台" as UC2
    usecase "图书留言" as UC3

    usecase "注册/登录" as UC4
    usecase "查看/修改个人信息" as UC5
    usecase "查看/修改相关图书信息" as UC6

    usecase "图书搜索" as UC7
    usecase "图书上传" as UC8
    usecase "图书求漂" as UC13
    usecase "图书起漂" as UC14
    usecase "查看图书地图" as UC9
    usecase "查看用户地图" as UC10

    usecase "编写留言" as UC11
    usecase "查看/更新图书留言" as UC12

    ' 建立用例关系，使用虚线表示 include 关系
    UC1 ..> UC4 : <<includes>>
    UC1 ..> UC5 : <<includes>>
    UC1 ..> UC6 : <<includes>>
    UC2 ..> UC7 : <<includes>>
    UC2 ..> UC8 : <<includes>>
    UC2 ..> UC9 : <<includes>>
    UC2 ..> UC13 : <<includes>>
    UC2 ..> UC14 : <<includes>>
    UC2 ..> UC10 : <<includes>>
    UC3 ..> UC11 : <<includes>>
    UC3 ..> UC12 : <<includes>>
    ' 普通用户与个人中心的关系
    普通用户 --> UC1
    普通用户 --> UC2
    普通用户 --> UC3
}
@enduml
