@startuml
class MessageActivity {
    - messageFragment: MessageFragment
}

class MessageFragment {
    - messageViewModel: MessageViewModel
}

class MessageViewModel {
    - messageService: MessageService
}

interface MessageService {
    + getMessages(): List<Message>
    + getMessage(messageId: Long): Message
}

class MessageServiceImpl {
    - messageRepository: MessageRepository
}

interface MessageRepository {
    + findAll(): List<Message>
    + findById(messageId: Long): Message
}

class MessageRepositoryImpl

class Message

MessageActivity *-- MessageFragment
MessageFragment --> MessageViewModel
MessageViewModel --> MessageService
MessageServiceImpl ..|> MessageService
MessageServiceImpl --> MessageRepository
MessageRepositoryImpl ..|> MessageRepository
MessageRepositoryImpl --> Message
@enduml