@startuml
skinparam packageStyle folder

folder "BookCrosserApp" {
    folder "app" {
        folder "src" {
            folder "main" {
                folder "java" {
                    folder "com.bookcrosser" {
                        folder "activities"
                        folder "adapters"
                        folder "fragments"
                        folder "models"
                        folder "services"
                        folder "utils"
                    }
                }
                folder "res" {
                    folder "drawable"
                    folder "layout"
                    folder "values"
                    folder "xml"
                }
                file "AndroidManifest.xml"
            }
            folder "test"
        }
        file "build.gradle"
    }
    folder "gradle"
    file "build.gradle"
}
@enduml